name: Layers dir links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 6 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.9
        with:
          args: >
            --verbose
            --exclude-loopback
            --exclude-mail
            --exclude validator.w3.org localhost
            --no-progress
            layers/**/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report [layers dir]
          content-filepath: ./lychee/out.md
          labels: report, automated issue
